From nginx:latest                         # from is used to mention the base image, we never build an image from scratch
ADD . /usr/share/nginx/html               # add all the content in current directory into this address of container, we are doing this as we do not need to mount volume in this case
                                        