FROM nginx:1.17.2-alpine   
# from is used to mention the base image, we never build an image from scratch                     
# we changed to 1.17.2-alpine in learning tags
ADD . /usr/share/nginx/html              
 # add all the content in current directory into this address of container, we are doing this as we do not need to mount volume in this case
                                        